# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}

      # run tests!
      - run: gradle test

      - run: gradle build

      - setup_remote_docker:
          version: 18.06.0-ce

      - run:
          name: Login to docker
          command: docker login -u zaidhoona -p 422682c9219fa74a4d1a48cc4ce357af9f401899 zaidhoona-docker-docker.bintray.io

      - run:
          name: Build Docker image
          command: docker build -t result-board/score-service:latest .

      - run:
          name: Tag image
          command: docker tag result-board/score-service:latest zaidhoona-docker-docker.bintray.io/result-board/score-service:latest

      - run:
          name: Push to artifactory
          command: docker push zaidhoona-docker-docker.bintray.io/result-board/score-service:latest
